### ISSUE TITLE
Power on off not reliable

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.twinkly#4]
Hi, I can turn on or off lights only once - then it reports error. Can you take a look please ? Also I see only on/off functionality, no color change possibility

**Comment by shaarkys** [comment]
8cbdbfe4-1cfa-4b64-bd89-39c33468417e

**Comment by shaarkys** [comment]
Btw static address assigned, I have latest firmware 
![SmartSelect_20191129-114705_Twinkly](https://user-images.githubusercontent.com/14859895/69863851-0bc7d600-129e-11ea-8210-18c0158145c5.jpg)

**Comment by jghaanstra** [comment]
Did you have the official Twinkly app open when you noticed this? Twinkly can only be controlled by one application at the same time.

**Comment by shaarkys** [comment]
I even force closed app on background - can only power off via Homey but can't power on again. I see in the log it immediately powers off (while the lights do nothing) ?

**Comment by jghaanstra** [comment]
Do you have the second generation Twinkly? Perhaps these are not fully compatible. The app has only been tested with first generation.

**Comment by shaarkys** [comment]
Yep, I have 2nd generation. Let me know if I can help somehow.

**Comment by shaarkys** [comment]
Btw, 2nd generation is really fantastic :-)

**Comment by shaarkys** [comment]
OK, I did the reset, lights reset and app. reinstall - without touching Homey at all...now it's working. Probably firmware upgrade caused something. In the meantime I also integrated with Google Home, but I don't think it's relevant.
