### ISSUE TITLE
aftger update white page in homey app on devices tab

### ISSUE THREAD

**Issue by B3rt** [jghaanstra/com.twinkly#7]
since last update to version 3.0.3 i have now a white page when i open the devices tab and when i try to open: more->apps->twinkly

I cannot add or control any device anymore in my homey app, this on all devices which are connected to my homey account.

I even cannot disable or remove the app!!

Please fix!

**Comment by jghaanstra** [comment]
This does not sound like an issue related to my app. It's either something with the smartphone app or with Homey itself. I would suggest rebooting Homey and force-close the smartphone app. If the problem persists you should contact Athom support about it.
