### ISSUE TITLE
when more twinkly leds are joined on function does not work

### ISSUE THREAD

**Issue by B3rt** [jghaanstra/com.twinkly#8]
Since last update the ON function does not work anymore when you group several twinkly (gen1) led strips

It is impossible to turn them on using the 'on' option, it does not matter which twinkly strip you try it on.
When on and you try off then they all go off.
(as group all joined twinkly led strips work as 1).

The only way to turn it on using Homey is to use the flow card 'demo on', when this (demon on) card is used all joined led strips are switched on.......  

This seems to me this is a bug, on the previous app i did not have this problem.
On previous app you could use the ON function on a random strip in the group and all strips in the group where switched on.

The off function/card works fine.

**Comment by jghaanstra** [comment]
It seems highly unlikely that the last update is the cause of your issue as I have not touched the on/off capability. Perhaps a firmware upgrade from Twinkly is the cause but this is our of my hands as there is no official API available and (as mentioned in the app store) no guarantees can be given that me app (keeps) working and functionality is limited to turning on/off (single strips) and recently dimming only.

If you know how to do a command line install you could of course go back to a previous version of the app and see if that works better for you.

**Comment by B3rt** [comment]
thx, but there was no firmware update,  i added a 3th led strip and created the group again, currently all strips run same firmware.

The strange thing is when you press ON in the app nothing happens, only the tile lights up and after a few seconds grey again.
This happens on all 3 the leds, i re-added the lights but it does not fix the problem.

When i turn the led group ON using the twinkly app it works fine, when i use demo on it also works in homey.
 
Luckily homey can turn it ON using the trick using card demo ON and then turn demo off again for normal operations.
So the bug is not that big enough for me to install using cli an older version.

I also hope a decent api will be available so grouping will be supported and also changing effects.
Thx for your time and work on the app.
